spring:
  application:
    name: test
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: app
    password: secure_app_password
#    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    default-schema: app
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: metrics,health

