openapi: 3.0.0
info:
  title: Task Creation API
  version: 1.0.0
  description: タスクを操作するAPI
paths:
  /tasks:
    post:
      summary: タスクを作成する
      description: このエンドポイントは新しいタスクを作成します。タスクにはタイトル、説明、および期限が含まれます。
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '200':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTaskResponse'
        '400':
          description: Bad Request - 入力値エラー
        '500':
          description: Internal Server Error - サーバー内部エラー
  /tasks/{taskId}:
    get:
      summary: 特定のタスクを取得する
      description: 指定されたIDのタスクの詳細情報を取得します
      operationId: getTask
      parameters:
        - name: taskId
          in: path
          required: true
          description: 取得するタスクのID
          schema:
            type: string
      responses:
        '200':
          description: Task retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTaskResponse'
        '404':
          description: Not Found - タスクが見つかりません
        '500':
          description: Internal Server Error - サーバー内部エラー

components:
  schemas:
    CreateTaskRequest:
      type: object
      properties:
        title:
          type: string
          description: The title of the task
          minLength: 1
        completeCondition:
          type: string
          description: The condition that must be met to complete the task
          maxLength: 500
        startDate:
          type: string
          format: date
          description: The start date for the task
        dueDate:
          type: string
          format: date
          description: The due date for the task
      required:
        - title
        - startDate
        - dueDate
    CreateTaskResponse:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        completeCondition:
          type: string
        startDate:
          type: string
          format: date
        dueDate:
          type: string
          format: date
        status:
          type: string
        isPostponed:
          type: boolean
      required:
        - id
        - title
        - startDate
        - dueDate
        - status
        - isPostponed
    GetTaskResponse:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        completeCondition:
          type: string
        startDate:
          type: string
          format: date
        dueDate:
          type: string
          format: date
        status:
          type: string
        isPostponed:
          type: boolean
      required:
        - id
        - title
        - startDate
        - dueDate
        - status
        - isPostponed
