version: '3.8'
services:
  db:
    image: postgres:16.9-bookworm
    container_name: postgres-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
      LANG: C.UTF-8
    ports:
      - "5432:5432"
volumes:
  db-data: