DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA IF NOT EXISTS app;

-- ローカルDBなので、平文を許容する
CREATE USER app WITH PASSWORD 'secure_app_password';
GRANT USAGE ON SCHEMA app TO app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app TO app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA app TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT USAGE, SELECT ON SEQUENCES TO app;
-- ローカルDBなので、平文を許容する
CREATE USER db_admin WITH PASSWORD 'secure_admin_password';
GRANT ALL PRIVILEGES ON SCHEMA app TO db_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA app TO db_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA app TO db_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL PRIVILEGES ON TABLES TO db_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL PRIVILEGES ON SEQUENCES TO db_admin;

ALTER USER app SET search_path = app;
ALTER USER db_admin SET search_path = app;
